#release configuration
#Tue Jul 22 18:18:38 GMT+03:00 2025
completedPhase=check-poms
exec.additionalArguments=--settings\=/Users/yusufcoskun/.m2/settings.xml -Psonatype-oss-release
exec.snapshotReleasePluginAllowed=false
preparationGoals=clean verify
projectVersionPolicyId=default
pushChanges=true
remoteTagging=true
scm.commentPrefix=[maven-release-plugin] 
scm.tag=1.0.0
scm.tagNameFormat=@{project.artifactId}-@{project.version}
scm.url=scm\:git\:git@github.com\:cadenzaflow/cadenzaflow-release-parent.git
