#release configuration
#Tue Jul 22 18:20:41 GMT+03:00 2025
completedPhase=generate-release-poms
exec.additionalArguments=--settings\=/Users/yusufcoskun/.m2/settings.xml -Psonatype-oss-release
exec.snapshotReleasePluginAllowed=false
preparationGoals=clean verify
project.dev.com.cadenzaflow\:cadenzaflow-release-parent=1.0.1-SNAPSHOT
project.rel.com.cadenzaflow\:cadenzaflow-release-parent=1.0.0
project.scm.com.cadenzaflow\:cadenzaflow-release-parent.connection=scm\:git\:git@github.com\:cadenzaflow/cadenzaflow-release-parent.git
project.scm.com.cadenzaflow\:cadenzaflow-release-parent.developerConnection=scm\:git\:git@github.com\:cadenzaflow/cadenzaflow-release-parent.git
project.scm.com.cadenzaflow\:cadenzaflow-release-parent.tag=1.0.0
project.scm.com.cadenzaflow\:cadenzaflow-release-parent.url=https\://github.com/cadenzaflow/cadenzaflow-release-parent
projectVersionPolicyId=default
pushChanges=true
remoteTagging=true
scm.commentPrefix=[maven-release-plugin] 
scm.tag=1.0.0
scm.tagNameFormat=@{project.artifactId}-@{project.version}
scm.url=scm\:git\:git@github.com\:cadenzaflow/cadenzaflow-release-parent.git
